framework:
    workflows:
        partner_management:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Partner
            initial_marking: start
            places:
                - start
                - application_pending
                - application_pending_priority
                - active
                - needs_profile_review
                - review_past_due
                - inactive
            transitions:
                submit:
                    from:
                        - start
                        - application_pending_priority
                        - inactive
                    to: application_pending
                submit_priority:
                    from:
                        - application_pending
                        - inactive
                    to: application_pending_priority
                activate:
                    from:
                        - application_pending
                        - application_pending_priority
                        - needs_profile_review
                        - review_past_due
                        - inactive
                    to: active
                flag_for_review:
                    from:
                        - application_pending
                        - application_pending_priority
                        - active
                        - review_past_due
                        - inactive
                    to: needs_profile_review
                flag_for_review_past_due:
                    from:
                        - application_pending
                        - application_pending_priority
                        - active
                        - needs_profile_review
                        - inactive
                    to: review_past_due
                deactivate:
                    from:
                        - application_pending
                        - application_pending_priority
                        - active
                        - needs_profile_review
                        - review_past_due
                    to: inactive