matrix:
    include:
        - language: node_js
          node_js:
              - '12'
              - node
          script:
              - yarn lint
              - yarn test
          cache:
              yarn: true
        - language: php
          php:
              - '7.3'
              - nightly
          cache:
              directories:
                  - $HOME/.composer/cache/files
                  - $HOME/symfony-bridge/.phpunit
          env:
              global:
                  - PHPUNIT_FLAGS="-v --coverage-text --coverage-clover"
                  - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
          before_install:
              - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              - chmod +x ./cc-test-reporter
              - ./cc-test-reporter before-build
          install:
              ./vendor/bin/simple-phpunit install
          before_script:
              - composer self-update
              - composer install --prefer-source --no-interaction --dev
          script:
              - vendor/bin/simple-phpunit $PHPUNIT_FLAGS
              # - vendor/bin/phpstan analyse
              - vendor/bin/phpcs
              # Pipe the coverage data to Code Climate
          after_script:
              - ./cc-test-reporter format-coverage -t clover -o coverage/codeclimate.json # Backend coverage
              - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json
    fast_finish: true
    allow_failures:
        - php: nightly

notifications:
    email: false
