matrix:
    include:
        - language: node_js
          node_js:
              - '12'
              - node
          script:
              - yarn lint
              - yarn test
          cache:
              yarn: true
        - language: php
          php:
              - '7.3'
              - nightly
          cache:
              directories:
                  - $HOME/.composer/cache/files
                  - $COMPOSER_BIN_DIR/.phpunit
          env:
              global:
                  - SYMFONY_PHPUNIT_DIR="$COMPOSER_BIN_DIR/.phpunit"
          before_install:
              - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              - chmod +x ./cc-test-reporter
              - ./cc-test-reporter before-build
          before_script:
              - composer self-update --2
              - composer install --prefer-source --no-interaction
              - psql -c 'create database coverd;' -U postgres
              - bin/console doctrine:schema:update --force
          script:
              - bin/console doctrine:schema:validate
              - bin/phpunit -v --coverage-clover clover.xml
              - vendor/bin/phpstan analyse --debug
              - vendor/bin/phpcs
          after_script:
              - ./cc-test-reporter format-coverage -t clover # Backend coverage
              - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json
    fast_finish: true
    allow_failures:
        - php: nightly
notifications:
    email: false
services:
    - postgresql
