# Use postgres/example user/password credentials
version: '3.1'

services:
    app:
        build:
          context: ./docker
          dockerfile: Dockerfile
        volumes:
            - ./:/app
        depends_on:
          - db
    nginx:
        image: nginx
        ports:
          - 8080:80
        volumes:
          - ./:/app:ro
          - ./docker/app.nginx.conf:/etc/nginx/conf.d/site.conf
        depends_on:
          - app
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: coverd
            POSTGRES_DB: coverd
        ports:
            - 5432:5432